# Generated by Django 3.1.5 on 2021-01-26 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Obsluga', '0007_auto_20210125_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerwacja_pokoju',
            name='pobyt',
        ),
        migrations.AddField(
            model_name='rezerwacja_pokoju',
            name='uzytkownik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pobyt',
            name='data_zakwaterowania',
            field=models.DateField(verbose_name='Data_zakwaterowania'),
        ),
        migrations.AlterField(
            model_name='rezerwacja_pokoju',
            name='ilosc_dni',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rezerwacja_uslugi_spa',
            name='ilosc_osob',
            field=models.IntegerField(),
        ),
    ]
