# Generated by Django 3.1.5 on 2021-01-27 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Obsluga', '0008_auto_20210126_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacja_uslugi_spa',
            name='uzytkownik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
