# Generated by Django 3.1.5 on 2021-01-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obsluga', '0009_rezerwacja_uslugi_spa_uzytkownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacja_pokoju',
            name='data_do',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='rezerwacja_pokoju',
            name='data_od',
            field=models.DateField(blank=True),
        ),
    ]
