# Generated by Django 3.1.5 on 2021-01-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obsluga', '0010_auto_20210127_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluga_spa',
            name='img',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
